#!/usr/bin/python

import os
import sys

f = open(sys.argv[1], 'r')
content = f.read()
cp866Content = content.encode('cp866')

filename = os.path.splitext(sys.argv[1])[0]
f = open(sys.argv[1], 'wb')
f.write(cp866Content)
